CREATE TABLE users(
    uid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(30) NOT NULL,
    passwordhash CHAR(60) NOT NULL,
    joindate TIMESTAMP NOT NULL,
    donator INT,
    email VARCHAR(60) NOT NULL,
    verified INT
);
CREATE TABLE tokens(
    uid INT NOT NULL,
    tokenhash CHAR(60) NOT NULL,
    FOREIGN KEY (uid) REFERENCES users (uid)
);
CREATE TABLE friends(
    uid1 INT NOT NULL,
    uid2 INT NOT NULL,
    FOREIGN KEY (uid1) REFERENCES users (uid),
    FOREIGN KEY (uid2) REFERENCES users (uid)
);
CREATE TABLE blocks(
    uid INT NOT NULL,
    annoyance INT NOT NULL,
    FOREIGN KEY (uid) REFERENCES users (uid),
    FOREIGN KEY (annoyance) REFERENCES users (uid)
);
