CREATE TABLE users(
    uid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(30) NOT NULL,
    passwordhash VARCHAR(128) NOT NULL,
    joindate TIMESTAMP NOT NULL,
    donator INT,
    email VARCHAR(60) NOT NULL UNIQUE,
    verified INT,
    postdefault INT,
    uimode INT,
    authlevel INT
);
CREATE TABLE tokens(
    uid INT NOT NULL PRIMARY KEY,
    session VARCHAR(128) NOT NULL,
    tokenhash VARCHAR(128) NOT NULL,
    expires TIMESTAMP,
    FOREIGN KEY (uid) REFERENCES users (uid)
);
CREATE TABLE resetcodes(
    uid INT NOT NULL PRIMARY KEY,
    codehash VARCHAR(128) NOT NULL,
    FOREIGN KEY (uid) REFERENCES users (uid);
);
CREATE TABLE friends(
    uid1 INT NOT NULL PRIMARY KEY,
    uid2 INT NOT NULL,
    FOREIGN KEY (uid1) REFERENCES users (uid),
    FOREIGN KEY (uid2) REFERENCES users (uid)
);
CREATE TABLE blocks(
    uid INT NOT NULL PRIMARY KEY,
    annoyance INT NOT NULL,
    FOREIGN KEY (uid) REFERENCES users (uid),
    FOREIGN KEY (annoyance) REFERENCES users (uid)
);
CREATE TABLE times(
    tid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid INT NOT NULL,
    privacy INT NOT NULL,
    start TIMESTAMP NOT NULL,
    duration INT NOT NULL,
    description TEXT,
    title VARCHAR(50) NOT NULL,
    FOREIGN KEY (uid) REFERENCES users (uid)
);
CREATE TABLE comments(
    cid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid INT NOT NULL,
    tid INT NOT NULL,
    content TEXT NOT NULL,
    FOREIGN KEY (uid) REFERENCES users (uid),
    FOREIGN KEY (tid) REFERENCES times (tid)
);
