-- Your SQL goes here
CREATE TABLE users(
    uid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(30) NOT NULL,
    passwordhash VARCHAR(128) NOT NULL,
    joindate TIMESTAMP NOT NULL,
    donator INT,
    email VARCHAR(60) NOT NULL UNIQUE,
    verified INT,
    postdefault INT,
    uimode INT
);
