-- Your SQL goes here
DROP TABLE tokens;
CREATE TABLE tokens(
    uid INT NOT NULL,
    session VARCHAR(128) NOT NULL,
    tokenhash VARCHAR(128) NOT NULL,
    expires TIMESTAMP,
    tid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FOREIGN KEY (uid) REFERENCES users (uid)
);
